AWSTemplateFormatVersion: 2010-09-09
Description: Get

Parameters:
  Stack:
    Description: Stack name
    Type: String
    Default: playground
  App:
    Description: Application name
    Type: String
    Default: women-in-media-gender-analysis
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - CODE
      - PROD
    Default: PROD
  DeployBucket:
    Description: Bucket where RiffRaff uploads artifacts on deploy
    Type: String
    Default: women-in-media-gender-analysis-dist

Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: logs
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
        - PolicyName: lambda
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                -  lambda:InvokeFunction
              Resource: "*"
        - PolicyName: api
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - execute-api:Invoke
              Resource: "*"
        - PolicyName: comprehend
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - comprehend:*
              Resource: "*"
        - PolicyName: s3
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - s3:*
              Resource: "*"

  GenderAnalysisLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${App}-${Stage}
      Code:
        S3Bucket:
          Ref: DeployBucket
        S3Key:
          !Sub Archive.zip
      Environment:
        Variables:
          Stage: !Ref Stage
          Stack: !Ref Stack
          App: !Ref App
      Description: Lambda that returns article analysis
      Handler: index.handler
      MemorySize: 512
      Role: !GetAtt ExecutionRole.Arn
      Runtime: nodejs8.10
      Timeout: 300

  GenderAnalysisApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: Api to call our lambda
      Name: !Sub ${App}-api-${Stage}

  GenderAnalysisApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref GenderAnalysisApi
      ParentId: !GetAtt [GenderAnalysisApi, RootResourceId]
      PathPart: getGenderAnalysis
    DependsOn: GenderAnalysisApi

  GenderAnalysisApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      RestApiId: !Ref GenderAnalysisApi
      ResourceId: !Ref GenderAnalysisApiResource
      HttpMethod: POST
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GenderAnalysisLambda.Arn}/invocations
    DependsOn:
      - GenderAnalysisApi
      - GenderAnalysisLambda
      - GenderAnalysisApiResource

  GenderAnalysisApiDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      Description: Deploys the API into an environment/stage
      RestApiId: !Ref GenderAnalysisApi
    DependsOn: GenderAnalysisApiMethod

  GenderAnalysisApiStageProd:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: !Ref Stage
      Description: Prod Stage
      RestApiId: !Ref GenderAnalysisApi
      DeploymentId: !Ref GenderAnalysisApiDeployment
      Variables:
        Stack: !Ref Stack
      MethodSettings:
        - ResourcePath: /getGenderAnalysis
          HttpMethod: POST
          MetricsEnabled: 'true'
          DataTraceEnabled: 'true'
          ThrottlingBurstLimit: '999'
    DependsOn:
      - GenderAnalysisApi
      - GenderAnalysisApiDeployment

  GenderAnalysisLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Sub ${App}-${Stage}
      Principal: apigateway.amazonaws.com
    DependsOn: GenderAnalysisLambda
